name: tayet_app_v2
description: A free Flutter project coded by Creative Tim.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1  # Incrementing build number for this revision

environment:
  sdk: ">=2.12.0 <3.0.0"  # Updated for latest Flutter compatibility

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.3.0 # Latest version as of July 2024
  carousel_slider: ^4.2.1           # Latest with null-safety
  url_launcher: ^6.1.10            # Latest with platform-specific handling
  font_awesome_flutter: ^10.4.0   # Latest for icon variety

  cupertino_icons: ^1.0.5  # Latest for consistency

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    # ... (Your existing image assets)

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700 # Corrected weight to match actual font file
